comptes:
    fixtures:
        carburants:
            -
                nom: Gazole
                rang: 1
            -
                nom: SP95
                rang: 2
            -
                nom: SP98
                rang: 3
        vehicules:
            -
                nom: Honda Varadero
                date_achat: 2011-10-11
                date_vente: 2012-04-28
                kilometrage_achat: 15815
                kilometrage_initial: 15815
                prix_achat: 2615
                carburant: 2
                capacite_reservoir: 17.7
                rang: 6
            -
                nom: Suzuki Bandit
                date_achat: 2012-05-05
                date_vente: 2013-06-25
                kilometrage_achat: 12280
                kilometrage_initial: 12463.85
                prix_achat: 2325
                carburant: 2
                capacite_reservoir: 19
                rang: 5
            -
                nom: Renault 25
                date_achat: 2010-01-01
                date_vente: 2013-07-26
                kilometrage_achat: 248845
                kilometrage_initial: 258926
                prix_achat: 1000
                carburant: 1
                capacite_reservoir: 66
                rang: 4
            -
                nom: Peugeot 406 coupé
                date_achat: 2013-07-06
                date_vente: 2016-04-23
                kilometrage_achat: 246743
                kilometrage_initial: 246755
                prix_achat: 2290
                carburant: 2
                capacite_reservoir: 70
                rang: 3
            -
                nom: Honda NC700X
                date_achat: 2013-10-31
                date_vente:
                kilometrage_achat: 24650
                kilometrage_initial: 24686
                prix_achat: 4790
                carburant: 2
                capacite_reservoir: 14.1
                rang: 1
            -
                nom: Suzuki Bandit 1200
                date_achat: 2016-10-30
                date_vente:
                kilometrage_achat: 100495.8
                kilometrage_initial: 100495.8
                prix_achat: 1000
                carburant: 2
                capacite_reservoir: 19
                rang: 2
        comptes:
            -
                nom: Compte courant
                numero: 00000000
                banque: Ma banque
                plafond: 0
                solde_initial: 1278.83
                date_ouverture: 2009-12-09
                date_fermeture:
                rang: 1
            -
                nom: Livret jeune
                numero: 00000000
                banque: Ma banque
                plafond: 1600
                solde_initial: 0
                date_ouverture: 2012-03-31
                date_fermeture:
                rang: 2
        categories:
            -
                nom: Revenus
                rang: 1
                subcategories:
                    -
                        nom: Salaire
                        rang: 1
            -
                nom: Logement
                rang: 2
                subcategories:
                    -
                        nom: Loyer
                        rang: 1
                    -
                        nom: Charges
                        rang: 2
                    -
                        nom: Assurance habitation
                        rang: 3
                    -
                        nom: Entretien
                        rang: 4
            -
                nom: Transports
                rang: 3
                subcategories:
                    -
                        nom: Carburant
                        rang: 1
                    -
                        nom: Péage & stationnement
                        rang: 3
                    -
                        nom: Assurances
                        rang: 2
                    -
                        nom: Achat véhicule
                        rang: 4
                    -
                        nom: Entretien véhicule
                        rang: 5
                        subcategories:
                            -
                                nom: Auto
                                rang: 1
                            -
                                nom: Moto
                                rang: 2
            -
                nom: Alimentation
                rang: 4
                subcategories:
                    -
                        nom: Courses
                        rang: 1
                    -
                        nom: Restaurants
                        rang: 2
            -
                nom: Impôts
                rang: 5
                subcategories:
                    -
                        nom: Impôts sur le revenu
                        rang: 1
                    -
                        nom: Taxe d'habitation
                        rang: 2
            -
                nom: Télécommunications
                rang: 6
                subcategories:
                    -
                        nom: Mobile
                        rang: 1
                    -
                        nom: Internet
                        rang: 2
            -
                nom: Santé
                rang: 7
                subcategories:
                    -
                        nom: Mutuelle
                        rang: 1
                    -
                        nom: Pharmacie
                        rang: 2
            -
                nom: Habillement
                rang: 8
            -
                nom: Loisirs & sorties
                rang: 9
            -
                nom: Achats divers
                rang: 10
            -
                nom: Cadeaux
                rang: 11
            -
                nom: Frais bancaires
                rang: 12
