# Configuration des handlers d'import de mouvements et de pleins.
# Chaque handler doit définir au moins les paramètres "name" et "extension",
# les autres sont libres et propres à chaque implémentation.
handlers:
    mouvements:
        # Identifiant du service d'import, ici "comptes_bundle.import.mouvements.cic.excel".
        cic.excel:
            # Nom de la source
            name: CIC - Excel
            # L'extension du fichier attendu par le handler d'import
            extension: xlsm
            # Le fichier Excel contient un compte par feuille.
            # Ce paramètre établit la correspondance entre les numéros de feuille
            # et les identifiants des comptes bancaires correspondants.
            sheets:
                1: 4
                2: 3
                3: 2
                4: 1
        # Identifiant du service d'import, ici "comptes_bundle.import.mouvements.cic.csv".
        cic.csv:
            # Nom de la source
            name: CIC - CSV
            # L'extension du fichier attendu par le handler d'import
            extension: csv
            # Le fichier CSV ne contient les mouvements que d'un seul compte.
            # Ce paramètre indique l'identifiant du compte sur lequel les importer.
            compte: 1
        # Identifiant du service d'import, ici "comptes_bundle.import.mouvements.caissedepargne.csv".
        caissedepargne.csv:
            # Nom de la source
            name: Caisse d'Épargne - CSV
            # L'extension du fichier attendu par le handler d'import
            extension: csv
            # Le fichier CSV ne contient les mouvements que d'un seul compte.
            # Ce paramètre indique l'identifiant du compte sur lequel les importer.
            compte: 1
    pleins:
        # Identifiant du service d'import, ici "comptes_bundle.import.pleins.mycars.xml".
        mycars.xml:
            # Nom de la source
            name: MyCars - XML
            # L'extension du fichier attendu par le handler d'import
            extension: xml
            # Le fichier XML fait référence à des véhicules.
            # Ce paramètre établit la correspondance entre le nom des véhicules
            # dans MyCars et les identifiants des véhicules correspondants.
            vehicules:
                Varadero: 1
                Bandit: 2
                Renault 25: 3
                406 coupé: 4
                NC700X: 5
        # Identifiant du service d'import, ici "comptes_bundle.import.pleins.mycars.csv".
        mycars.csv:
            # Nom de la source
            name: MyCars - CSV
            # L'extension du fichier attendu par le handler d'import
            extension: csv
            # Le fichier CSV fait référence à des véhicules.
            # Ce paramètre établit la correspondance entre le nom des véhicules
            # dans MyCars et les identifiants des véhicules correspondants.
            vehicules:
                Varadero: 1
                Bandit: 2
                Renault 25: 3
                406 coupé: 4
                NC700X: 5

# Liste de correspondance entre les mots-clés de mouvements
# tels qu'ils apparaissent dans les fichiers d'import,
# et les identifiants de leurs catégories.
keywords:
    FREE: 22
    SALAIRE: 2
    INTERET: 2
    EDF: 5
    MAAF: 11
    AXA: 26
    EAU: 5
    LOYER: 4
    CIC-ASSURANCES: 6
    HAUTDEBIT: 24
    TELECOM: 24
    AUTOROUTE: 10
    DONALD: 18
    CARBURANT: 9
    MOBILE: 23
    CINE: 29
    ASSURANCE: 11
    CINEVILLE: 29
    MOTOREP: 15
    NORAUTO: 14
    FREEMOBILE: 23
    QUICK: 18
    ORANGE: 23
    KFC: 18
    PHARMA: 27
    DAFY: 15
    CPAM: 25
    MATERIEL: 30
    CHRONODRIVE: 2
    DONALD'S: 18
    SOINS: 26
    JULES: 28
    STAGE: 2
    IKEA: 3
    CELIO: 28
    CADEAU: 31
    TISSEO-REGIE: 8
    BRICE: 28
    PHARM: 27
    URSSAF: 20
    PATHE: 29
    COVOITURAGE: 8
    COIFFEUR: 28
    BOULANGER: 3
    AUTOSUR: 13
    BROOKLYN: 28
    KDO: 31
    MCDONALDS: 18
    GAUMONT: 29
    IMPOT: 19
    KART: 29
    FLY: 3
    SUBWAY: 18
    CADEAUX: 31
    BRIOCHE: 16
    PNEUS: 13
    ANNIV: 31
    EUROBOWL: 29
    FLUNCH: 18
    ANNIVERSAIRE: 31
    PNEU: 13
    CINEATLANTIS: 29
    BECANERIE: 15
    PREFECTURE: 19
    CHAUSSURES: 28
    CHEQUIER: 33