# Configuration des handlers d'import de mouvements et de pleins.
# Chaque handler doit définir au moins les paramètres "name", "description"
# et "extension", les autres sont libres et propres à chaque implémentation.
handlers:
    mouvements:
        # Identifiant du service d'import, ici "comptes_bundle.import.mouvements.cic.excel".
        cic.excel:
            # Nom de la source
            name: CIC - Excel
            # Description de la source. HTML autorisé.
            description: |-
                Import multicompte.
                Feuille 1 : livret A, feuille 2 : livret jeune, feuille 3 : compte courant.
            # L'extension du fichier attendu par le handler d'import
            extension: xlsm
            # Le fichier Excel contient un compte par feuille.
            # Ce paramètre établit la correspondance entre les numéros de feuille
            # et les identifiants des comptes bancaires correspondants.
            sheets:
                1: 3
                2: 2
                3: 1
        # Identifiant du service d'import, ici "comptes_bundle.import.mouvements.cic.csv".
        cic.csv:
            # Nom de la source
            name: CIC - CSV
            # Description de la source. HTML autorisé.
            description: |-
                Import monocompte, montants sur deux colonnes, dates au format JJ/MM/AAAA, séparateur : point-virgule, séparateur décimales : virgule.
                Destination : compte courant.
            # L'extension du fichier attendu par le handler d'import
            extension: csv
            # Le fichier CSV ne contient les mouvements que d'un seul compte.
            # Ce paramètre indique l'identifiant du compte sur lequel les importer.
            compte: 1
        # Identifiant du service d'import, ici "comptes_bundle.import.mouvements.caissedepargne.csv".
        caissedepargne.csv:
            # Nom de la source
            name: Caisse d'Épargne - CSV
            # Description de la source. HTML autorisé.
            description: |-
                Import monocompte.
                Destination : compte courant.
            # L'extension du fichier attendu par le handler d'import
            extension: csv
            # Le fichier CSV ne contient les mouvements que d'un seul compte.
            # Ce paramètre indique l'identifiant du compte sur lequel les importer.
            compte: 1
    pleins:
        # Identifiant du service d'import, ici "comptes_bundle.import.pleins.mycars.xml".
        mycars.xml:
            # Nom de la source
            name: MyCars - XML
            # Description de la source. HTML autorisé.
            description: |-
                Import depuis l'application Android <a href="https://play.google.com/store/apps/details?id=com.aguirre.android.mycar.activity">MyCars</a>.
            # L'extension du fichier attendu par le handler d'import
            extension: xml
            # Le fichier XML fait référence à des véhicules.
            # Ce paramètre établit la correspondance entre le nom des véhicules
            # dans MyCars et les identifiants des véhicules correspondants.
            vehicules:
                Varadero: 1
                Bandit: 2
                Renault 25: 3
                406 coupé: 4
                NC700X: 5
        # Identifiant du service d'import, ici "comptes_bundle.import.pleins.mycars.csv".
        mycars.csv:
            # Nom de la source
            name: MyCars - CSV
            # Description de la source. HTML autorisé.
            description: |-
                Import depuis l'application Android <a href="https://play.google.com/store/apps/details?id=com.aguirre.android.mycar.activity">MyCars</a>.
            # L'extension du fichier attendu par le handler d'import
            extension: csv
            # Le fichier CSV fait référence à des véhicules.
            # Ce paramètre établit la correspondance entre le nom des véhicules
            # dans MyCars et les identifiants des véhicules correspondants.
            vehicules:
                Varadero: 1
                Bandit: 2
                Renault 25: 3
                406 coupé: 4
                NC700X: 5