ComptesBundle\Entity\Carburant:
    type: entity
    table: carburants
    repositoryClass: ComptesBundle\Entity\Repository\CarburantRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
        rang:
            type: integer
            nullable: true
    oneToMany:
        vehicules:
            targetEntity: ComptesBundle\Entity\Vehicule
            cascade:
                - persist
            mappedBy: carburant
            orderBy:
                rang: ASC
