ComptesBundle\Entity\Categorie:
    type: entity
    table: categories
    repositoryClass: ComptesBundle\Entity\Repository\CategorieRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
        rang:
            type: integer
            nullable: true
    manyToOne:
        categorieParente:
            targetEntity: ComptesBundle\Entity\Categorie
            cascade:
                - persist
            inversedBy: categoriesFilles
            joinColumns:
                categorie_parente_id:
                    onDelete: 'SET NULL'
    oneToMany:
        categoriesFilles:
            targetEntity: ComptesBundle\Entity\Categorie
            mappedBy: categorieParente
            orderBy:
                rang: ASC
        mouvements:
            targetEntity: ComptesBundle\Entity\Mouvement
            cascade:
                - persist
            mappedBy: categorie
            orderBy:
                date: ASC
        keywords:
            targetEntity: ComptesBundle\Entity\Keyword
            cascade:
                - persist
            mappedBy: categorie
