ComptesBundle\Entity\Keyword:
    type: entity
    table: keywords
    repositoryClass: ComptesBundle\Entity\Repository\KeywordRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        word:
            type: string
            unique: true
    manyToOne:
        categorie:
            targetEntity: ComptesBundle\Entity\Categorie
            cascade:
                - persist
            inversedBy: keywords
            joinColumn:
                nullable: false
