ComptesBundle\Entity\Mouvement:
    type: entity
    table: mouvements
    repositoryClass: ComptesBundle\Entity\Repository\MouvementRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        date:
            type: date
        montant:
            type: decimal
            scale: 2
            precision: 8
        description:
            type: string
    manyToOne:
        categorie:
            targetEntity: ComptesBundle\Entity\Categorie
            cascade:
                - persist
            inversedBy: mouvements
        compte:
            targetEntity: ComptesBundle\Entity\Compte
            cascade:
                - persist
            inversedBy: mouvements
            joinColumn:
                nullable: false
