# Dashboard
dashboard:
    path:     /
    defaults: { _controller: ComptesCoreBundle:Dashboard:index }

# Liste des comptes bancaires
comptes_comptes:
    path:     /comptes
    defaults: { _controller: ComptesCoreBundle:Compte:index }

# Visualisation d'un compte bancaire
comptes_compte:
    path:     /comptes/{compte_id}
    defaults: { _controller: ComptesCoreBundle:Compte:show }
    requirements:
        compte_id: \d+

# Liste des catégories
categories_categories:
    path:     /categories
    defaults: { _controller: ComptesCoreBundle:Categorie:index }

# Visualisation d'une catégorie
categories_categorie:
    path:     /categories/{categorie_id}
    defaults: { _controller: ComptesCoreBundle:Categorie:show }
    requirements:
        categorie_id: \d+

# Liste des pleins
pleins_pleins:
    path:     /pleins
    defaults: { _controller: ComptesCoreBundle:Plein:index }

# Liste des véhicules
vehicules_vehicules:
    path:     /vehicules
    defaults: { _controller: ComptesCoreBundle:Vehicule:index }

# Import des mouvements bancaires
import_mouvements:
    path:     /import/mouvements
    defaults: { _controller: ComptesCoreBundle:Import:mouvements }

# Import des pleins de carburant
import_pleins:
    path:     /import/pleins
    defaults: { _controller: ComptesCoreBundle:Import:pleins }

# Édition d'une liste de mouvements
mouvements_edit:
    path:     /mouvements/edit
    defaults: { _controller: ComptesCoreBundle:Mouvement:edit }

# Édition d'une liste de pleins
pleins_edit:
    path:     /pleins/edit
    defaults: { _controller: ComptesCoreBundle:Plein:edit }